<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <title>Request Access for {{ $appName }}</title>
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
            color: #1a1a1a;
            background: #f7f9fc;
        }

        .wrapper {
            max-width: 720px;
            margin: 0 auto;
            padding: 24px;
            background: #fff;
        }

        .header {
            border-bottom: 2px solid #0d6efd;
            margin-bottom: 16px;
        }

        .header h2 {
            margin: 0 0 6px;
            color: #0d6efd;
        }

        .meta {
            font-size: 13px;
            color: #555;
        }

        .section-title {
            margin: 22px 0 8px;
            font-weight: 700;
            color: #0d6efd;
        }

        table {
            border-collapse: collapse;
            width: 100%;
        }

        th,
        td {
            border: 1px solid #e5e7eb;
            padding: 8px 10px;
            vertical-align: top;
        }

        th {
            background: #f3f4f6;
            text-align: left;
            width: 220px;
        }

        .footer {
            margin-top: 20px;
            font-size: 12px;
            color: #6b7280;
        }
    </style>
</head>

<body>
    <div class="wrapper">

        <!-- HEADER -->
        <div class="header">
            <h2>{{ $appName }} Notification</h2>
            <div class="meta">
                Request Access Submission
            </div>
        </div>

        <!-- GREETING -->
        <p>Halo,</p>
        <p>Terdapat permintaan akses baru dengan detail berikut:</p>

        <!-- IDENTITY -->
        <div class="section-title">Requestor Information</div>
        <table>
            <tr>
                <th>Name</th>
                <td>{{ $data['name'] }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ $data['email'] }}</td>
            </tr>
            <tr>
                <th>Department</th>
                <td>{{ $data['department'] }}</td>
            </tr>
            <tr>
                <th>Plant</th>
                <td>{{ $data['plant'] }}</td>
            </tr>
            <tr>
                <th>Purpose</th>
                <td>{{ $data['purpose'] }}</td>
            </tr>
        </table>

        <!-- FOOTER -->
        <div class="footer">
            This email was automatically generated by {{ $appName }}.<br>
            Please do not reply to this email.
        </div>

    </div>
</body>

</html>
